/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniCommon */

#ifndef _Included_com_qpidnetwork_request_RequestJniCommon
#define _Included_com_qpidnetwork_request_RequestJniCommon
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_qpidnetwork_request_RequestJniCommon
 * Method:    TranslateText
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnTranslateTextCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniCommon_TranslateText
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
