/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJni */

#ifndef _Included_com_qpidnetwork_request_RequestJni
#define _Included_com_qpidnetwork_request_RequestJni
#ifdef __cplusplus
extern "C" {
#endif
#undef com_qpidnetwork_request_RequestJni_InvalidRequestId
#define com_qpidnetwork_request_RequestJni_InvalidRequestId -1i64
/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    SetLogDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_RequestJni_SetLogDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    SetVersionCode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_RequestJni_SetVersionCode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    SetCookiesDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_RequestJni_SetCookiesDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    SetWebSite
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_RequestJni_SetWebSite
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    SetPublicWebSite
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_RequestJni_SetPublicWebSite
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    SetAuthorization
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_RequestJni_SetAuthorization
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    CleanCookies
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_RequestJni_CleanCookies
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    GetCookies
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qpidnetwork_request_RequestJni_GetCookies
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    StopRequest
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_RequestJni_StopRequest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    SetRequestFinishCallback
 * Signature: (Lcom/qpidnetwork/request/OnRequestFinishCallback;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_RequestJni_SetRequestFinishCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    StopAllRequest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_RequestJni_StopAllRequest
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    GetDeviceId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qpidnetwork_request_RequestJni_GetDeviceId
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    SetDeviceId
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_RequestJni_SetDeviceId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    GetDownloadContentLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qpidnetwork_request_RequestJni_GetDownloadContentLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    GetRecvLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qpidnetwork_request_RequestJni_GetRecvLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    GetUploadContentLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qpidnetwork_request_RequestJni_GetUploadContentLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_qpidnetwork_request_RequestJni
 * Method:    GetSendLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_qpidnetwork_request_RequestJni_GetSendLength
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
