/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniMan */

#ifndef _Included_com_qpidnetwork_request_RequestJniMan
#define _Included_com_qpidnetwork_request_RequestJniMan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    ModifyPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_ModifyPassword
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    EmotionConfig
 * Signature: (Lcom/qpidnetwork/request/OnOtherEmotionConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_EmotionConfig
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    PhoneInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIILjava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_PhoneInfo
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    VersionCheck
 * Signature: (Lcom/qpidnetwork/request/OnVersionCheckCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_VersionCheck
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    SynConfig
 * Signature: (Lcom/qpidnetwork/request/OnSynConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_SynConfig
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    UploadCrashLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_UploadCrashLog
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
