/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_ConfigManagerJni */

#ifndef _Included_com_qpidnetwork_request_ConfigManagerJni
#define _Included_com_qpidnetwork_request_ConfigManagerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_ConfigManagerJni
 * Method:    AddCallback
 * Signature: (Lcom/qpidnetwork/request/OnConfigManagerCallback;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_ConfigManagerJni_AddCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_ConfigManagerJni
 * Method:    RemoveCallback
 * Signature: (Lcom/qpidnetwork/request/OnConfigManagerCallback;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_ConfigManagerJni_RemoveCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_ConfigManagerJni
 * Method:    Sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_ConfigManagerJni_Sync
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
