/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniMan */

#ifndef _Included_com_qpidnetwork_request_RequestJniMan
#define _Included_com_qpidnetwork_request_RequestJniMan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_RequestJniMan
 * Method:    QueryManList
 * Signature: (IIILjava/lang/String;IIIZLcom/qpidnetwork/request/OnQueryManListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniMan_QueryManList
  (JNIEnv *, jclass, jint, jint, jint, jstring, jint, jint, jint, jboolean, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniMan
 * Method:    QueryManDetail
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnQueryManDetailCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniMan_QueryManDetail
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniMan
 * Method:    QueryFavourList
 * Signature: (Lcom/qpidnetwork/request/OnQueryFavourListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniMan_QueryFavourList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniMan
 * Method:    AddFavourites
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniMan_AddFavourites
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniMan
 * Method:    RemoveFavourites
 * Signature: ([Ljava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniMan_RemoveFavourites
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniMan
 * Method:    QueryManRecentChatList
 * Signature: (IIILcom/qpidnetwork/request/OnQueryManRecentChatListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniMan_QueryManRecentChatList
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniMan
 * Method:    QueryManRecentViewList
 * Signature: (Lcom/qpidnetwork/request/OnQueryManRecentViewListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniMan_QueryManRecentViewList
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
