/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_LoginManagerJni */

#ifndef _Included_com_qpidnetwork_request_LoginManagerJni
#define _Included_com_qpidnetwork_request_LoginManagerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_LoginManagerJni
 * Method:    SetLoginCallback
 * Signature: (Lcom/qpidnetwork/request/OnLoginManagerCallback;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_LoginManagerJni_SetLoginCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_LoginManagerJni
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_LoginManagerJni_Login
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_qpidnetwork_request_LoginManagerJni
 * Method:    Logout
 * Signature: (jint)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_request_LoginManagerJni_Logout
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_qpidnetwork_request_LoginManagerJni
 * Method:    GetUser
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qpidnetwork_request_LoginManagerJni_GetUser
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_request_LoginManagerJni
 * Method:    GetPassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qpidnetwork_request_LoginManagerJni_GetPassword
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
