/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniAlbum */

#ifndef _Included_com_qpidnetwork_request_RequestJniAlbum
#define _Included_com_qpidnetwork_request_RequestJniAlbum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_RequestJniAlbum
 * Method:    QueryAlbumList
 * Signature: (Lcom/qpidnetwork/request/OnQueryAlbumListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAlbum_QueryAlbumList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAlbum
 * Method:    CreateAlbum
 * Signature: (ILcom/lang/String;Lcom/lang/String;Lcom/qpidnetwork/request/OnCreateAlbumCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAlbum_CreateAlbum
  (JNIEnv *, jclass, jint, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAlbum
 * Method:    EditAlbum
 * Signature: (Lcom/lang/String;ILcom/lang/String;Lcom/lang/String;Lcom/qpidnetwork/request/OnEditAlbumCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAlbum_EditAlbum
  (JNIEnv *, jclass, jstring, jint, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAlbum
 * Method:    DeleteAlbum
 * Signature: (Lcom/lang/String;ILcom/qpidnetwork/request/OnDeleteAlbumCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAlbum_DeleteAlbum
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAlbum
 * Method:    QueryAlbumPhotoList
 * Signature: (Lcom/lang/String;Lcom/qpidnetwork/request/OnQueryAlbumPhotoListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAlbum_QueryAlbumPhotoList
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAlbum
 * Method:    AddAlbumPhoto
 * Signature: (Lcom/lang/String;Lcom/lang/String;Lcom/lang/String;Lcom/qpidnetwork/request/OnSaveAlbumPhotoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAlbum_AddAlbumPhoto
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAlbum
 * Method:    EditAlbumPhoto
 * Signature: (Lcom/lang/String;Lcom/lang/String;Lcom/qpidnetwork/request/OnEditAlbumPhotoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAlbum_EditAlbumPhoto
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAlbum
 * Method:    QueryAlbumVideoList
 * Signature: (Lcom/lang/String;Lcom/qpidnetwork/request/OnQueryAlbumVideoListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAlbum_QueryAlbumVideoList
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAlbum
 * Method:    UploadVideoFile
 * Signature: (Lcom/lang/String;Lcom/lang/String;ILcom/lang/String;ILcom/lang/String;Lcom/lang/String;Lcom/qpidnetwork/request/OnUploadVideoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAlbum_UploadVideoFile
  (JNIEnv *, jclass, jstring, jstring, jint, jstring, jint, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAlbum
 * Method:    AddAlbumVideo
 * Signature: (Lcom/lang/String;Lcom/lang/String;Lcom/lang/String;Lcom/lang/String;Lcom/lang/String;Lcom/qpidnetwork/request/OnSaveAlbumVideoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAlbum_AddAlbumVideo
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAlbum
 * Method:    EditAlbumVideo
 * Signature: (Lcom/lang/String;Lcom/lang/String;Lcom/lang/String;Lcom/qpidnetwork/request/OnEditAlbumVideoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAlbum_EditAlbumVideo
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);


#ifdef __cplusplus
}
#endif
#endif
