/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_tool_ImageHandler */

#ifndef _Included_com_qpidnetwork_tool_ImageHandler
#define _Included_com_qpidnetwork_tool_ImageHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_tool_ImageHandler
 * Method:    SetLogPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_tool_ImageHandler_SetLogPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qpidnetwork_tool_ImageHandler
 * Method:    ConvertEmotionPng
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_tool_ImageHandler_ConvertEmotionPng
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
